/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Photo: typeof import('./src/components/Photo/Photo.vue')['default']
    PhotoForm: typeof import('./src/components/Photo/PhotoForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
